name: Build debug APK

on:
  push:
    branches: [ work ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Cache Gradle packages
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gemini-OCR-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
